require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/apartements", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Apartement. As you add validations to Apartement, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Apartement.create! valid_attributes
      get apartements_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      apartement = Apartement.create! valid_attributes
      get apartement_url(apartement)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_apartement_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      apartement = Apartement.create! valid_attributes
      get edit_apartement_url(apartement)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Apartement" do
        expect {
          post apartements_url, params: { apartement: valid_attributes }
        }.to change(Apartement, :count).by(1)
      end

      it "redirects to the created apartement" do
        post apartements_url, params: { apartement: valid_attributes }
        expect(response).to redirect_to(apartement_url(Apartement.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Apartement" do
        expect {
          post apartements_url, params: { apartement: invalid_attributes }
        }.to change(Apartement, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post apartements_url, params: { apartement: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested apartement" do
        apartement = Apartement.create! valid_attributes
        patch apartement_url(apartement), params: { apartement: new_attributes }
        apartement.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the apartement" do
        apartement = Apartement.create! valid_attributes
        patch apartement_url(apartement), params: { apartement: new_attributes }
        apartement.reload
        expect(response).to redirect_to(apartement_url(apartement))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        apartement = Apartement.create! valid_attributes
        patch apartement_url(apartement), params: { apartement: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested apartement" do
      apartement = Apartement.create! valid_attributes
      expect {
        delete apartement_url(apartement)
      }.to change(Apartement, :count).by(-1)
    end

    it "redirects to the apartements list" do
      apartement = Apartement.create! valid_attributes
      delete apartement_url(apartement)
      expect(response).to redirect_to(apartements_url)
    end
  end
end
